import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import { Activity, Coins, Gamepad2, LayoutDashboard, LogOut, Menu, PackageOpen, ShieldAlert, Store, WalletCards, X } from 'lucide-react';
import { jjkApi, type InventoryItem, type Player, type Summary } from '@/lib/jjk-api';
import OverviewPage from '@/pages/OverviewPage';
import ArcadePage from '@/pages/ArcadePage';
import { InventoryPage, MarketPage, TreasuryPage } from '@/pages/SectionPages';
import AdminPage from '@/pages/AdminPage';
const nav = [{ path: '/', label: 'Overview', icon: LayoutDashboard }, { path: '/arcade', label: 'Arcade', icon: Gamepad2 }, { path: '/market', label: 'Market', icon: Store }, { path: '/treasury', label: 'Treasury', icon: WalletCards }, { path: '/inventory', label: 'Inventory', icon: PackageOpen }];
export default function App() { const [location, setLocation] = useLocation(); const [player, setPlayer] = useState<Player | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [loading, setLoading] = useState(true); const [authError, setAuthError] = useState(''); const [menu, setMenu] = useState(false); const [inventory, setInventory] = useState<InventoryItem[]>([]); const [inventoryLoading, setInventoryLoading] = useState(false); const [inventoryError, setInventoryError] = useState(''); const [actionId, setActionId] = useState<number | null>(null);
 useEffect(() => { const token = localStorage.getItem('jjk_token'); if (!token) { setLoading(false); return; } Promise.all([jjkApi.me(), jjkApi.summary()]).then(([me, overview]) => { setPlayer(me); setSummary(overview); }).catch(() => { localStorage.removeItem('jjk_token'); }).finally(() => setLoading(false)); }, []);
 async function openInventory() { setLocation('/inventory'); setInventoryLoading(true); try { const response = await jjkApi.inventory(); setInventory(response.items || []); } catch (cause) { setInventoryError(cause instanceof Error ? cause.message : 'Inventory unavailable.'); } finally { setInventoryLoading(false); } }
 async function equip(item: InventoryItem) { setActionId(item.id); try { await jjkApi.equip(item.id); setInventory(items => items.filter(candidate => candidate.id !== item.id)); setPlayer(await jjkApi.me()); } catch (cause) { setInventoryError(cause instanceof Error ? cause.message : 'Could not equip item.'); } finally { setActionId(null); } }
 async function signOut() { try { await jjkApi.logout(); } catch { /* local identity still clears */ } localStorage.removeItem('jjk_token'); setPlayer(null); setSummary(null); setLocation('/'); }
 if (loading) return <Loading />; if (!player || !summary) return <Login error={authError} setError={setAuthError} onSuccess={(result) => { localStorage.setItem('jjk_token', result.token); setPlayer(result.player); void jjkApi.summary().then(setSummary); }} />;
 const updateBalance = (yen: number) => setPlayer(current => current ? { ...current, yen } : current); const page = location === '/arcade' ? <ArcadePage onBalanceChange={updateBalance} /> : location === '/market' ? <MarketPage onBalanceChange={updateBalance} /> : location === '/treasury' ? <TreasuryPage /> : location === '/inventory' ? <InventoryPage items={inventory} loading={inventoryLoading} error={inventoryError} actionId={actionId} onEquip={equip} onBack={() => setLocation('/')} /> : location === '/admin' && player.is_admin ? <AdminPage /> : <OverviewPage player={player} summary={summary} onNavigate={setLocation} />;
 return <div className="app-shell"><aside className={`side-rail ${menu ? 'open' : ''}`}><div className="brand"><span className="brand-mark">J</span><span><b>JJK RPG</b><small>Command center</small></span><button type="button" className="mobile-close" onClick={() => setMenu(false)}><X size={18} /></button></div><div className="rail-label">Navigation</div><nav>{nav.map(item => <button type="button" key={item.path} onClick={() => { if (item.path === '/inventory') void openInventory(); else setLocation(item.path); setMenu(false); }} className={`nav-item ${location === item.path ? 'active' : ''}`}><item.icon size={17} /><span>{item.label}</span>{item.path === '/arcade' && <i>NEW</i>}</button>)}{player.is_admin && <button type="button" onClick={() => { setLocation('/admin'); setMenu(false); }} className={`nav-item admin-nav ${location === '/admin' ? 'active' : ''}`}><ShieldAlert size={17} /><span>Admin console</span></button>}</nav><div className="rail-bottom"><div className="rail-status"><span className="pulse-dot" /><span><b>Systems live</b><small>Bot sync active</small></span></div><button type="button" onClick={() => void signOut()} className="signout"><LogOut size={15} /> Sign out</button></div></aside><div className="main-shell"><header className="top-bar"><button type="button" className="mobile-menu" onClick={() => setMenu(true)}><Menu size={20} /></button><div className="crumb"><Activity size={14} className="text-[#55d8e5]" /><span>JJK RPG</span><b>/</b><strong>{location === '/' ? 'Overview' : location.slice(1)}</strong></div><div className="top-actions"><div className="wallet"><Coins size={15} /><span>¥{player.yen.toLocaleString()}</span></div><div className="avatar">{player.display_name.slice(0, 1).toUpperCase()}</div></div></header><main className="content-shell">{page}</main></div></div>; }
function Login({ error, setError, onSuccess }: { error: string; setError: (value: string) => void; onSuccess: (result: { token: string; player: Player }) => void }) { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { onSuccess(await jjkApi.passwordLogin(username, password)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Sign in failed.'); } finally { setBusy(false); } } return <main className="login-page"><div className="login-art" /><div className="login-card"><div className="brand login-brand"><span className="brand-mark">J</span><span><b>JJK RPG</b><small>Player command center</small></span></div><p className="eyebrow text-[#55d8e5]">Secure gateway // 01</p><h1>Resume your<br /><em>progression.</em></h1><p className="login-copy">The new player portal for battles, games, the curse economy, and your growing arsenal.</p><form onSubmit={submit}><label>Dashboard username<input value={username} onChange={event => setUsername(event.target.value)} placeholder="your_username" required /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Your private password" required /></label><button type="submit" className="primary-action full" disabled={busy}>{busy ? 'Authenticating…' : 'Enter JJK RPG →'}</button>{error && <p className="error-banner">{error}</p>}</form><p className="login-foot">Create or reset access through the bot with <b>/web</b> and <b>/webreset</b>.</p></div></main>; }
function Loading() { return <main className="loading-state full-screen"><span className="spinner" /><p className="eyebrow">Synchronizing player vault</p></main>; }
