import { useEffect, useState } from 'react';
import { Check, Coins, Loader2, Save, ShieldAlert, Users, X } from 'lucide-react';
import { jjkApi, type AdminOverview, type AdminPrice } from '@/lib/jjk-api';

export default function AdminPage() {
  const [data, setData] = useState<AdminOverview | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState<number | string | null>(null);
  async function load() { try { setData(await jjkApi.adminOverview()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Admin data unavailable.'); } }
  useEffect(() => { void load(); }, []);
  async function review(id: number, status: 'approved' | 'rejected') { setBusy(`topup-${id}`); try { await jjkApi.reviewTopup(id, status); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Review failed.'); } finally { setBusy(null); } }
  async function adjust(userId: number) { const raw = window.prompt('Yen adjustment (+ to grant, - to remove)'); if (!raw) return; const amount = Number(raw); if (!Number.isFinite(amount)) return; setBusy(`player-${userId}`); try { await jjkApi.adjustYen(userId, amount); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Adjustment failed.'); } finally { setBusy(null); } }
  async function savePrice(source: 'shop_item' | 'character', item: AdminPrice, value: string) { const price = Number(value); if (!Number.isInteger(price) || price < 1) return setError('Prices must be whole yen amounts greater than zero.'); setBusy(`${source}-${item.id}`); try { await jjkApi.updatePrice(source, item.id, price); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Price update failed.'); } finally { setBusy(null); } }
  return <div className="page-wrap"><div className="page-heading"><div><p className="eyebrow text-[#f05b63]">Owner console // restricted</p><h1 className="page-title">Run the game world.</h1><p className="page-lede">Review receipts, monitor the economy, and edit live shop and character prices whenever you need.</p></div><div className="admin-chip"><ShieldAlert size={15} /> Owner access</div></div>{error && <p role="alert" className="error-banner">{error}</p>}{!data ? <div className="loading-state"><Loader2 className="animate-spin" /> Loading command data…</div> : <><div className={`delivery-health ${data.receipt_forwarding_configured ? 'ready' : 'blocked'}`}>{data.receipt_forwarding_configured ? '✓ Telegram receipt forwarding is configured and ready.' : '⚠ Telegram receipt forwarding is not configured. Add BOT_TOKEN and OWNER_ID to the production API environment before accepting top-ups.'}</div><div className="admin-stats"><Stat label="Players" value={data.economy.player_count.toLocaleString()} icon={Users} /><Stat label="Yen in economy" value={`¥${data.economy.total_yen.toLocaleString()}`} icon={Coins} /><Stat label="Arcade runs / 24h" value={data.economy.runs_24h.toLocaleString()} icon={ShieldAlert} /><Stat label="Rewards paid / 24h" value={`¥${data.economy.paid_24h.toLocaleString()}`} icon={Check} /></div><div className="admin-grid"><ReceiptQueue data={data} busy={busy} review={review} /><PlayerRegistry data={data} busy={busy} adjust={adjust} /></div><PriceCatalog title="Shop item prices" eyebrow="Economy controls // live" source="shop_item" items={data.prices.shop_items} busy={busy} onSave={savePrice} /><PriceCatalog title="Character prices" eyebrow="Roster controls // live" source="character" items={data.prices.characters} busy={busy} onSave={savePrice} /></>}</div>;
}
function ReceiptQueue({ data, busy, review }: { data: AdminOverview; busy: number | string | null; review: (id: number, status: 'approved' | 'rejected') => Promise<void> }) { return <section className="panel p-5"><div className="panel-heading"><div><p className="eyebrow text-[#ffd166]">Treasury queue</p><h2 className="section-title">Receipt approvals</h2></div><span className="badge">{data.topups.filter(item => item.status === 'pending').length} pending</span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>ID</th><th>Player</th><th>Amount</th><th>Delivery</th><th>Status</th><th /></tr></thead><tbody>{data.topups.map(item => <tr key={item.topup_id}><td className="font-mono">#{item.topup_id}</td><td>{item.display_name || item.user_id}<small>{item.reference}</small></td><td className="font-mono">¥{item.amount.toLocaleString()}</td><td><span className={`status ${item.delivery_status === 'sent' ? 'approved' : 'pending'}`}>{item.delivery_status || 'pending'}</span></td><td><span className={`status ${item.status}`}>{item.status}</span></td><td>{item.status === 'pending' && <div className="row-actions"><button title="Approve" type="button" disabled={busy === `topup-${item.topup_id}`} onClick={() => void review(item.topup_id, 'approved')}><Check size={14} /></button><button title="Reject" type="button" disabled={busy === `topup-${item.topup_id}`} onClick={() => void review(item.topup_id, 'rejected')}><X size={14} /></button></div>}</td></tr>)}</tbody></table></div></section>; }
function PlayerRegistry({ data, busy, adjust }: { data: AdminOverview; busy: number | string | null; adjust: (id: number) => Promise<void> }) { return <section className="panel p-5"><div className="panel-heading"><div><p className="eyebrow text-[#55d8e5]">Player registry</p><h2 className="section-title">Live roster</h2></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Player</th><th>Level</th><th>Wallet</th><th /></tr></thead><tbody>{data.players.map(item => <tr key={item.user_id}><td>{item.display_name}<small>@{item.username || 'unknown'} · {item.rank}</small></td><td>{item.level}</td><td className="font-mono">¥{item.yen.toLocaleString()}</td><td><button className="adjust-button" type="button" onClick={() => void adjust(item.user_id)} disabled={busy === `player-${item.user_id}`}>Adjust</button></td></tr>)}</tbody></table></div></section>; }
function PriceCatalog({ title, eyebrow, source, items, busy, onSave }: { title: string; eyebrow: string; source: 'shop_item' | 'character'; items: AdminPrice[]; busy: number | string | null; onSave: (source: 'shop_item' | 'character', item: AdminPrice, value: string) => Promise<void> }) { return <section className="panel p-5 price-panel"><div className="panel-heading"><div><p className="eyebrow text-[#9be15d]">{eyebrow}</p><h2 className="section-title">{title}</h2></div><span className="badge">{items.length} editable</span></div><div className="price-grid">{items.map(item => <PriceRow key={item.id} item={item} source={source} busy={busy} onSave={onSave} />)}</div></section>; }
function PriceRow({ item, source, busy, onSave }: { item: AdminPrice; source: 'shop_item' | 'character'; busy: number | string | null; onSave: (source: 'shop_item' | 'character', item: AdminPrice, value: string) => Promise<void> }) { const [value, setValue] = useState(String(item.price)); const changed = value !== String(item.price); return <div className="price-row"><div><b>{item.name}</b><small>{item.type || item.grade || 'Product'} · ID {item.id}</small></div><div className="price-editor"><span>¥</span><input aria-label={`${item.name} price`} type="number" min="1" value={value} onChange={event => setValue(event.target.value)} /><button type="button" disabled={!changed || busy === `${source}-${item.id}`} onClick={() => void onSave(source, item, value)} title="Save price"><Save size={14} /></button></div></div>; }
function Stat({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Coins }) { return <div className="admin-stat"><Icon size={17} className="text-[#55d8e5]" /><p className="eyebrow">{label}</p><strong>{value}</strong></div>; }
