import { useState } from 'react';
import { CircleDot, Crosshair, Dribbble, Goal, Loader2, Trophy } from 'lucide-react';
import { jjkApi } from '@/lib/jjk-api';

type Game = 'football' | 'basketball' | 'pool';
const games: Record<Game, { name: string; eyebrow: string; description: string; icon: typeof Goal; labels: [string, string]; colors: string }> = {
  football: { name: 'Penalty Lab', eyebrow: 'Football // 01', description: 'Read the keeper, choose your corner, and strike with controlled power.', icon: Goal, labels: ['Corner', 'Power'], colors: 'from-[#55d8e5]/20 to-[#162a40]' },
  basketball: { name: 'Three-Point Lab', eyebrow: 'Basketball // 02', description: 'Tune the release arc and power for a clean swish from deep.', icon: Dribbble, labels: ['Arc', 'Power'], colors: 'from-[#f05b63]/20 to-[#2b1828]' },
  pool: { name: 'Break Room', eyebrow: 'Pool // 03', description: 'Line the cue ball, set your power, and crack the opening break.', icon: CircleDot, labels: ['Angle', 'Power'], colors: 'from-[#ab75ff]/20 to-[#211936]' },
};
export default function ArcadePage({ onBalanceChange }: { onBalanceChange: (yen: number) => void }) {
  const [game, setGame] = useState<Game>('football'); const [first, setFirst] = useState(.5); const [power, setPower] = useState(.65); const [busy, setBusy] = useState(false); const [result, setResult] = useState<{ success: boolean; reward: number; distance?: number } | null>(null); const [error, setError] = useState(''); const selected = games[game]; const Icon = selected.icon;
  function pick(next: Game) { setGame(next); setResult(null); setError(''); }
  async function play() { setBusy(true); setError(''); setResult(null); try { const response = await jjkApi.skillGame(game, game === 'basketball' ? { arc: first, power } : { angle: first, power }); setResult(response); onBalanceChange(response.balance); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The arena could not settle the play.'); } finally { setBusy(false); } }
  return <div className="page-wrap"><div className="page-heading"><div><p className="eyebrow text-[#ffd166]">JJK RPG // player arena</p><h1 className="page-title">Play for the highlight reel.</h1><p className="page-lede">These are real playable skill games, not placeholder buttons. Your controls are sent to the server, scored, and rewarded in yen.</p></div><div className="live-chip"><span className="pulse-dot" /> Settlement live</div></div><div className="game-tabs">{(Object.keys(games) as Game[]).map(key => { const item = games[key]; const TabIcon = item.icon; return <button key={key} type="button" onClick={() => pick(key)} className={`game-tab ${game === key ? 'active' : ''}`}><TabIcon size={17} /><span><b>{item.name}</b><small>{item.eyebrow}</small></span></button>; })}</div><section className={`play-stage bg-gradient-to-br ${selected.colors}`}><div className="play-stage-copy"><div className="icon-orb"><Icon size={28} /></div><p className="eyebrow mt-6">{selected.eyebrow}</p><h2 className="stage-title">{selected.name}</h2><p className="mt-3 max-w-md text-sm leading-6 text-[#aebbd0]">{selected.description}</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><Control label={selected.labels[0]} value={first} setValue={setFirst} accent={game === 'basketball' ? '#f05b63' : '#55d8e5'} /><Control label={selected.labels[1]} value={power} setValue={setPower} accent="#ffd166" /></div><button type="button" onClick={() => void play()} disabled={busy} className="play-button mt-8">{busy ? <><Loader2 size={17} className="animate-spin" /> Judging play…</> : <><Trophy size={17} /> Take the shot</>}</button>{result && <div className={`result-banner ${result.success ? 'success' : 'miss'}`}><span>{result.success ? 'PLAY MADE' : 'CLOSE CALL'}</span><b>{result.success ? `+¥${result.reward.toLocaleString()}` : 'No reward this run'}</b><small>{result.distance ? `Precision gap ${result.distance}` : 'Adjust your controls and try again after cooldown.'}</small></div>}{error && <p role="alert" className="mt-4 text-sm text-[#ff9ea6]">{error}</p>}</div><div className="pitch-visual" aria-hidden="true"><div className="visual-ring ring-one" /><div className="visual-ring ring-two" /><div className="visual-ball"><CircleDot size={36} /></div><div className="visual-target"><Crosshair size={30} /></div></div></section><div className="mt-5 grid gap-4 md:grid-cols-3"><InfoCard title="Server scored" detail="Your action is validated and settled by the bot API." /><InfoCard title="Cooldown protected" detail="Short cooldowns keep rewards fair for every player." /><InfoCard title="Game economy" detail="Rewards increase your real in-game yen balance." /></div></div>;
}
function Control({ label, value, setValue, accent }: { label: string; value: number; setValue: (value: number) => void; accent: string }) { return <label className="control-card"><div className="flex justify-between text-xs uppercase tracking-[.16em] text-[#93a1b7]"><span>{label}</span><b style={{ color: accent }}>{Math.round(value * 100)}%</b></div><input aria-label={label} type="range" min="0" max="1" step=".01" value={value} onChange={event => setValue(Number(event.target.value))} style={{ accentColor: accent }} /><div className="range-hints"><span>0</span><span>Precision</span><span>100</span></div></label>; }
function InfoCard({ title, detail }: { title: string; detail: string }) { return <article className="info-card"><p className="eyebrow text-[#55d8e5]">{title}</p><p className="mt-2 text-sm leading-5 text-[#b0bdd0]">{detail}</p></article>; }
