import { ArrowUpRight, CalendarCheck2, ChevronRight, PackageOpen, ShieldCheck, Sparkles, Target, Trophy } from 'lucide-react';
import type { Player, Summary } from '@/lib/jjk-api';

type Props = { player: Player; summary: Summary; onOpenInventory: () => void };

export default function FeatureBoard({ player, summary, onOpenInventory }: Props) {
  const streak = summary.daily_status?.streak || 0;
  const canClaim = Boolean(summary.daily_status?.can_claim);
  const xpPercent = player.xp_needed ? Math.min(100, Math.round(player.xp / player.xp_needed * 100)) : 0;
  return <section className="mt-5 grid gap-3 lg:grid-cols-3" aria-label="Player operations"><article className="panel p-5 transition hover:-translate-y-1"><div className="relative flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center border border-[#f05b63]/30 bg-[#f05b63]/10 text-[#f05b63]"><Target size={18} /></div><span className="badge">MISSION</span></div><p className="eyebrow mt-5 text-[#f05b63]">Daily ritual</p><h3 className="mt-1 font-display text-xl font-semibold">{streak} day streak</h3><p className="mt-2 text-xs leading-5 text-[#91a0b5]">{canClaim ? 'A reward is ready in the Telegram mission board.' : 'Complete your next bot mission to extend the streak.'}</p><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4 text-xs"><span className={canClaim ? 'tone-green' : 'text-[#91a0b5]'}>{canClaim ? 'Reward ready' : 'Tracking live'}</span><CalendarCheck2 size={15} className="text-[#55d8e5]" /></div></article><article className="panel p-5 transition hover:-translate-y-1"><div className="relative flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center border border-[#ab75ff]/30 bg-[#ab75ff]/10 text-[#ab75ff]"><Trophy size={18} /></div><span className="badge !border-[#ab75ff]/40 !bg-[#ab75ff]/10 !text-[#c9a9ff]">RANK</span></div><p className="eyebrow mt-5 text-[#ab75ff]">Progression ladder</p><h3 className="mt-1 font-display text-xl font-semibold">{player.rank}</h3><p className="mt-2 text-xs leading-5 text-[#91a0b5]">Level {player.level} · {player.wins} wins · {player.losses} losses</p><div className="mt-5"><div className="mb-2 flex justify-between text-[10px] uppercase tracking-[.14em] text-[#8492ab]"><span>Next breakthrough</span><span className="font-mono">{xpPercent}%</span></div><div className="meter"><div className="meter-fill" style={{ width: `${xpPercent}%`, background: '#ab75ff', boxShadow: '0 0 12px rgba(171,117,255,.65)' }} /></div></div></article><article className="panel p-5 transition hover:-translate-y-1"><div className="relative flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center border border-[#55d8e5]/30 bg-[#55d8e5]/10 text-[#55d8e5]"><PackageOpen size={18} /></div><span className="badge !border-[#55d8e5]/40 !bg-[#55d8e5]/10 !text-[#55d8e5]">ARSENAL</span></div><p className="eyebrow mt-5 text-[#55d8e5]">Cursed tools</p><h3 className="mt-1 font-display text-xl font-semibold">Loadout control</h3><p className="mt-2 text-xs leading-5 text-[#91a0b5]">Inspect effects, equip weapons, and keep your battle readiness current.</p><button type="button" onClick={onOpenInventory} className="mt-5 inline-flex items-center gap-2 border-t border-white/10 pt-4 text-xs font-semibold text-[#55d8e5] transition hover:text-white">Open inventory <ChevronRight size={14} /></button></article></section>;
}
